### ISSUE TITLE
ncores flag not used used in analyze.py

### ISSUE THREAD

**Issue by MSiggel** [bio-phys/MDBenchmark#113]
As far as I can tell the ncores flag is not used in the code and we are always guessing the number of cores. I would suggest we either remove this flag or fix its functionality.

**Comment by mimischi** [comment]
We were using it before, but did not port the functionality, when we pulled out the plotting.

https://github.com/bio-phys/MDBenchmark/blob/62a072c8e48f121c82ee5ae1f3523b25a2a521c3/mdbenchmark/analyze.py#L94-L100

I guess we could just enable this feature, so that users still relying on `mdbenchmark analyze --plot` will get what they are expecting:

https://github.com/bio-phys/MDBenchmark/blob/0ffe0dd46a062b32a6bdb95c4a6b58dc67cd0f7a/mdbenchmark/analyze.py#L133
