### ISSUE TITLE
Multiple simulations per node

### ISSUE THREAD

**Issue by mimischi** [bio-phys/MDBenchmark#167]
Running multiple simulations per node is beneficial when the node contains GPUs. We want to include this functionality in `version-3` and release it soon. This issue should outline the functionality and some considerations required for the implementation.

# Generate
  - Add new `--multidir` option.
  - Restrict `--min-nodes` and `--max-nodes` to `1`. Warn the user that their input will be ignored.
  - Generate `Treant` in parent folder and separate `Treant` for every multidir child repetition.
    - Parent folder has `multidir=True` category, whereas each child has `multidir_child=True`.
  - Add `_multidir` to folder with engine version, i.e., `2018.6_gpu_multidir`.
# Analyze
  - Ignore parent `Treant` for analysis, look only in child `Treant` for `md.log` file.
  - Calculate average of all child `md.log` files for performance.
  - Print one line for the average in the console.
# Plot
  - Same considerations as for `analyze`.
  - Add a new plot type to showcase the differences between 1 sim./node, 2 sim./node and 4 sim./node?
  - Different plotting types for either 1 sim./node or multidir data?

**Comment by ksebaz** [comment]
I am not sure whether splitting the multidir directory on the engine-level is good/necessary. In the `gpu` case, that option is just a flag, but in the multidir-case, the user might want to scan for various numbers of simulations. So manipulating the benchmark directory name with the number of simulations (e.g., n001_r04_t10_nsim4) is necessary anyhow. In that case splitting on the engine-level in addition seems superfluous to me.

Adding a child-`Treant` to the multidir output-folder is also not strictly necessary. In any case, there will be either one log-file on the benchmark-folder level, or a few in various subfolders. Since currently the log-file is searched for by globbing, one can just extend that globbing to the subfolders. Not creating `Treants` for the multidir-output would have the benefit that we don't have to blow up the code with if statements when to use the parent- and when to use the child-`Treant`. Also I am not sure at the moment how multiple simulation will work with namd. So if we can get away without chaning the treant-structure for the moment could be a good idea. What do you think @mimischi?

Restricting the number of nodes is currently also not strictly necessary. The gromacs-multidir option works also with multiple nodes. So one can also just leave the plot routing as is and just add the multidir group to the plot.

The number of ranks per node must be such that nranks*nnodes is a multiple of number of simulations.

I have a prelminary version in my fork in the multidir branch. `generate`, `analyze` and `plot` work as described above (without the check for the number of ranks). I will create a pull request so you can have a look.

**Comment by ksebaz** [comment]
see #168

**Comment by mimischi** [comment]
> Adding a child-`Treant` to the multidir output-folder is also not strictly necessary. In any case, there will be either one log-file on the benchmark-folder level, or a few in various subfolders. Since currently the log-file is searched for by globbing, one can just extend that globbing to the subfolders. Not creating `Treants` for the multidir-output would have the benefit that we don't have to blow up the code with if statements when to use the parent- and when to use the child-`Treant`. Also I am not sure at the moment how multiple simulation will work with namd. So if we can get away without chaning the treant-structure for the moment could be a good idea. What do you think @mimischi?

I agree we do not need to separate at the engine-level.

**Comment by mimischi** [comment]
I'm closing this issue, as the original PR #168 was merged. Any further enhancements should be discussed in new issues.
